//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Case.Study.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public long Error_ID { get; set; }
        public string Error_Code { get; set; }
        public string Error_StackTrace { get; set; }
        public string Error_InnerException { get; set; }
        public Nullable<System.DateTime> Error_DateTime { get; set; }
    }
}
