//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Case.Study.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long User_ID { get; set; }
        public string User_Email { get; set; }
        public Nullable<bool> User_EmailConfirmed { get; set; }
        public string User_Password { get; set; }
        public string User_PasswordHash { get; set; }
        public string User_UserName { get; set; }
        public Nullable<int> User_RoleID { get; set; }
        public Nullable<bool> User_Active { get; set; }
        public Nullable<System.DateTime> User_CreateDate { get; set; }
        public string User_FullName { get; set; }
    
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
